spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  storage:
    type: s3
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
      region: ${AWS_REGION}

  aws:
    sqs:
      document-queue-url: ${AWS_SQS_DOCUMENT_QUEUE_URL}
      polling-interval-ms: ${AWS_SQS_POLLING_INTERVAL_MS:10000}