spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  flyway:
    enabled: true

app:
  storage:
    type: s3
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
      region: ${AWS_REGION}